version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.0
    - 1.12.1
  - dependency-name: simplecov
    versions:
    - 0.21.2
  - dependency-name: jbuilder
    versions:
    - 2.11.2
  - dependency-name: json
    versions:
    - 2.5.1
  - dependency-name: sinatra-activerecord
    versions:
    - 2.0.22
  - dependency-name: database_cleaner
    versions:
    - 2.0.1
