AllCops:
  Exclude:
    - spec/**/*.rb
    - db/**/*.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Max: 20
