default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: corbot_dev
  username: corbot
  password: corbot

test:
  <<: *default
  database: corbot_test
  username: corbot
  password: corbot

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
