development:
  adapter: postgresql
  encoding: unicode
  database: corbot_dev
  pool: 10
  username: corbot
  password: corbot

test:
  adapter: postgresql
  encoding: unicode
  database: corbot_test
  pool: 10
  username: corbot
  password: corbot
