name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: corbot
          POSTGRES_PASSWORD: corbot
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Install PostgreSQL 11 client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Install CodeClimate Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
        if: github.ref == 'refs/heads/master'

      - name: Build and run rspec
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
        env:
          COVERAGE: 1
          RACK_ENV: test

      - name: Report code coverage
        run: ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
        if: github.ref == 'refs/heads/master'
